### ISSUE TITLE
Indicator for multiple items is indistinctz

### ISSUE THREAD

**Issue by ToxiClay** [I-am-Erk/CDDA-Tilesets#380]
As the attached image shows, the indicator for "This tile has multiple items" can be indistinct, especially on items that share the same color.

Suggestion: Adopt Undead People's indicator (a green plus), in shape or color or both.

![image](https://user-images.githubusercontent.com/13796683/103156947-1b08a400-477c-11eb-8db7-39da66211bf9.png)

**Comment by acepleiades** [comment]
I can imagine that if I started playing CDDA with UDP (and kept playing for a long time with it), the difference would be blatant and even annoying. However, I used to play with MSX, stopped playing for a long time, and came back straight to UltiCa with a blurry memory of the previous tileset and have been playing with it since. Are you sure that it's not something one could get used to? Because given my experience as I described it, I never felt those icons were hard to see.

**Comment by acepleiades** [comment]
Also, I'm just noticing this, but wouldn't it be good if item sprites were displayed over vehicle trunks?

**Comment by ToxiClay** [comment]
I feel like the color is simply too close on the cargo spaces, especially if you're zoomed out a level. I'm not sure it's something one could simply 'get used to,' but I suppose it's possible?

**Comment by acepleiades** [comment]
It might only be a problem for gray tiles, but it's a problem nonetheless, considering a lot of people are used to UDP. I' like to hear @int-ua 's opinion on this

**Comment by int-ua** [comment]
I support @ToxiClay in that it's hardly noticeable. Are you sure it was done by UDP and not some previous contributor to that same tileset. You keep referring to it as UDP, but it's **MSX++**UDP, it wasn't built from scratch :) Anyway, how about three bright green dots?

**Comment by ToxiClay** [comment]
Yeah, bright green dots would be perfect. That's enough to even be noticeable _on_ green tiles, I think.

**Comment by int-ua** [comment]
![highlight_item2_4x](https://user-images.githubusercontent.com/1585431/103252443-9ee1ac80-4985-11eb-9e1f-a6c3a468ff85.png)
